name: Obfuscate and Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  obfuscate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Create distribution directory
      run: |
        mkdir -p dist
        rsync -av --exclude='.git' --exclude='.github' --exclude='dist' ./ dist/
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Update parser.js import
      run: |
        sed -i 's|import questionData from "./dat/QuestionData.json" with {type: "json"};|import questionData from "./dat/QuestionData.js";|g' dist/js/parser.js
    
    - name: Convert JSON to JS module
      run: |
        echo "export default " > dist/dat/QuestionData.js
        cat dist/dat/QuestionData.json >> dist/dat/QuestionData.js
        rm dist/dat/QuestionData.json
    
    - name: Install javascript-obfuscator
      run: npm install -g javascript-obfuscator
    
    - name: Obfuscate QuestionData.js
      run: |
        javascript-obfuscator dist/dat/QuestionData.js \
          --output dist/dat/QuestionData.js \
          --compact true \
          --control-flow-flattening true \
          --dead-code-injection true \
          --string-array true \
          --string-array-encoding base64 \
          --string-array-rotate true \
          --string-array-shuffle true \
          --string-array-threshold 0.75 \
          --self-defending true
    
    - name: Deploy to production branch
      run: |
        cd dist
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git init
        git add .
        git commit -m "Obfuscated build from ${{ github.sha }}"
        git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:production
